---
title: "The **seqtsne** package"
author: "Joseph R Boyd"
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
    %\VignetteIndexEntry{Overview and Use Cases}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---

<style type = "text/css"> em { font-weight: bold; } </style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    dpi=60
)
```

# Synopsis
seq - tee - snee

`r Githubpkg("jrboyd/seqtsne")` 

# Features

* tsne on ChIP-seq data

# Functions

* `ssv*` - most primary user facing functions are prefixed by ssv



# Installation and Loading

## From github

```{r bioc install, eval=FALSE}
## try http:// if https:// URLs are not supported
# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("seqtsne")
devtools::install_github("jrboyd/seqtsne")
```

## Load the library
```{r load seqtsne, message=FALSE}
library(seqtsne)
```

## Load optional useful libraries
```{r load optional libs, message = FALSE}
library(GenomicRanges)
library(data.table)
library(cowplot)
library(seqsetvis)
theme_set(cowplot::theme_cowplot())
```

```{r}
files = c(
    dir("/slipstream/galaxy/uploads/working/qc_framework/output/", 
        pattern = "K4.+_pooled$", full.names = TRUE),
    dir("/slipstream/galaxy/uploads/working/qc_framework/output/", 
        pattern = "K27.+_pooled$", full.names = TRUE)
)
#assemble peak calls and sample
peaks = dir(files, pattern = "pooled_peaks.narrowPeak", full.names = TRUE)
olaps = ssvOverlapIntervalSets(easyLoad_narrowPeak(peaks))
olaps = olaps[rowSums(as.data.frame(mcols(olaps))) > 3] 
length(olaps)
set.seed(0)
query_gr = sample(olaps, 100)
query_gr = resize(query_gr, 5000, fix = "center")
query_gr$id = names(query_gr)
#create config from bws
bws = dir(files, pattern = "pooled_FE.bw", full.names = TRUE)
qdt = data.table(file = bws)
qdt[, c("cell", "mark") := tstrsplit(basename(file), "_", keep = 1:2)]
options("mc.cores" = 20)
tsne_input = fetch_tsne_mat(qdt, query_gr)
tsne_res = run_tsne(tsne_input$tsne_mat, perplexity = 10)
n_points = 6
color_mapping = c("H3K4ME3" = "forestgreen",
                  "H3K27ME3" = "firebrick1", 
                  "H3K4AC" = "blue", 
                  "H3K27AC" = "purple")
```

```{r basic plot, fig.width=13, fig.height=4}
ggplot(tsne_res, aes(x = tx, y = ty, color = cell)) + 
    geom_point() +
    facet_wrap("cell")
```

```{r, fig.width=5, fig.height=5}
img = make_tsne_img(tsne_input$bw_dt, tsne_res, n_points = n_points, 
                    line_colors = color_mapping)
img_res = plot_tsne_img(img$images_dt, n_points = n_points, min_size = 0)
img_res$plot
```

```{r, fig.width=7.5, fig.height=3}
img_byCell = make_tsne_img(tsne_input$bw_dt, tsne_res, n_points = n_points, 
                    line_colors = c("H3K4ME3" = "forestgreen",
                                    "H3K27ME3" = "firebrick1", 
                                    "H3K4AC" = "blue", 
                                    "H3K27AC" = "purple"), 
                    facet_by = "cell")
img_byCell_res = plot_tsne_img_byCell(img_byCell$images_dt, img_byCell$tsne_dt, n_points = n_points)
img_byCell_res$plot

```

```{r, fig.width=8, fig.height=4}
vel_res = plot_velocity_arrows(tsne_res = tsne_res, cell_a = "MCF10A", cell_b = "MCF7")
plot_grid(plotlist = vel_res)
```

```{r, fig.width=4, fig.height=3}
plot_velocity_arrows_binned(tsne_res, cell_a = "MCF10A", cell_b = "MCF7", n_points = n_points)
```

```{r, fig.width=4, fig.height=3}
plot_velocity_arrows_binned(tsne_res, points_as_background = FALSE,
                            cell_a = "MCF10A", cell_b = "MCF7", 
                            n_points = n_points, p = img_res$plot)
```

```{r, fig.width=6, fig.height=3}
plot_profiles_selected(tsne_input$bw_dt, 
                       qgr = query_gr[1], 
                       qcells = c("MCF10A", "MCF7"), 
                       tss_ids = names(query_gr)[1], 
                       color_mapping = color_mapping)
```


